### ISSUE TITLE
george pleas cydio

### ISSUE THREAD

**Issue by jacc** [GeoSn0w/OsirisJailbreak12#1]
pleas

**Comment by kooz123** [comment]
pls Grorge cydio soonn

**Comment by oganessium** [comment]
pleas George Snow, need I need cydia

**Comment by exofeel** [comment]
pleas I beg of urself, I need to usage of cydio

**Comment by shibbbe** [comment]
pleas 🙏🙏🙏

**Comment by xFahrenheightx** [comment]
iso 13 cydio pls eta wen

**Comment by nn9dev** [comment]
ETaaA^2 for cidya !? Plea!!! Will jeelbrek s0n!

**Comment by GeoSn0w** [comment]
Sorry. Osiris will only come with Filza and Dropbear by default.
