### ISSUE TITLE
dyld_shared_cache_extract_dylibs failed

### ISSUE THREAD

**Issue by TheNinty** [GeoSn0w/OsirisJailbreak12#4]
Got it to build, but now I get this error. "dyld_shared_cache_extract_dylibs failed"

There are also 2 warning but I'll only mention one because the other is just an appicon error:

Semantic Issue > Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior.

I'm also running on a hackintosh if this is important. I don't think it is considering I've built many apps on here but I figure it was worth mentioning.

**Comment by TheNinty** [comment]
Fixed it by unpairing then repairing the device through xcode

**Comment by GeoSn0w** [comment]
Glad you fixed this
