### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by ioudeveldhuis** [GeoSn0w/OsirisJailbreak12#7]
When I open the project and try to compile it I run into the following error:

```
/XXX/projects/OsirisJailbreak12/osirisJB12/Osiris/Osiris Post/QiLin.h:240:27: Unknown type name '_STRUCT_ARM_THREAD_STATE64'
```

I saw the other issue with the compile error but that one doesn't resolve my issue.

**Comment by gi097** [comment]
What Xcode version are you using? It compiles fine for me on XCode 10. I created a PR in this repo which fixes some missing file issues.

**Comment by ioudeveldhuis** [comment]
Found out that the issue is caused by selecting the simulator instead of my device. It compile's perfectly when I select my device. Closing this issue.
